import java.text.MessageFormat;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
class Mobile {
    private String name;
    private String color;
    private String brand;

    public Mobile(String name, String color, String brand) {
        this.name = name;
        this.color = color;
        this.brand = brand;
    }

    public void call(String message) {
        System.out.println(MessageFormat.format("Message : [{0}]",message));
    }

    @Override
    public String toString() {
        return MessageFormat.format("name:[{0}], color:[{1}], brand:[{2}]",name,color,brand);
    }
}

class iPhone extends  Mobile{
    static int messageLimit = 100;
    public iPhone(String name, String color, String brand) {
        super(name, color, brand);
    }
    @Override
    public void call(String message) {
        if (message.length() > messageLimit)
            System.out.println("<iPhone> Message cannot be sent");
        else
            System.out.println("<iPhone>Message : "+"["+ message + "]");
    }
}

class AndroidMobile extends  Mobile{
    static int messageLimit = 90;
    public AndroidMobile(String name, String color, String brand) {
        super(name, color, brand);
    }
    @Override
    public void call(String message) {
        if (message.length() > messageLimit)
            System.out.println("<Android> Message cannot be sent");
        else
            System.out.println("<Android>Message : "+"["+ message + "]");
    }
}

class Person {
    private String name;

    private Mobile mobile;

    public Person(String name, Mobile mobile) {
        this.name = name;
        this.mobile = mobile;
    }

    public void setMobile(Mobile mobile) {
        this.mobile = mobile;
    }

    public void call(String message) {
        mobile.call(message);
    }

}

class IphoneRobot {
    private String name;
    private iPhone iphone;

    public void call(String message) {
        iphone.call(message);
    }
}
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile("My phone","blue","NOKIA");
        mobile.call("calling");
        System.out.println(mobile.toString());

        Person person = new Person("Person",new iPhone("iPhone","black","Apple"));
        person.call("Hello world");
        person.setMobile(new AndroidMobile("Android","white","Google"));
        person.call("Hello world");
    }
}
